modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/webbukkit/dynmap/issues"
[[mods]]
modId="dynmap"
version="${version}"
displayName="Dynmap"
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="mikeprimm"
# The description text for the mod (multi line!) (#mandatory)
description='''
Dynamic, Google-maps style rendered maps for your Minecraft server
'''

[[dependencies.dynmap]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="SERVER"
[[dependencies.dynmap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="SERVER"
